{
    "status": 1,
    "sidoCd": 11,
    "sidoName": "서울특별시",
    "cpElectionDistrictId": "2111601",
    "electionDistrictName": "강서구갑",
    "imageUrl": "1267EF3743AC94CC1F64C5",
    "sidoShortName": "서울",
    "electionDistrictShortName": "강서갑",
    "cpPartyId": "100",
    "partyName": "민주통합당",
    "partyShortName": "민주",
    "pollingScore": "64187",
    "scoringRate": "48.7",
    "cpPersonId": "100101102",
    "electionSymbol": "2",
    "candidateName": "신기남",
    "rankgin": 0,
    "statusName": "당선",
    "countRate": "100.0"
}